### ISSUE TITLE
perl-socket6 module missing

### ISSUE THREAD

**Issue by x86128** [biwhite/docker-rancid-git#1]
When run _rancid-run_ script i'm getting the following in logs:
`Can't locate Socket6.pm in @INC (you may need to install the Socket6 module) (@INC contains: /usr/local/lib/perl5/site_perl /usr/local/share/perl5/site_perl /usr/lib/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/core_perl /usr/share/perl5/core_perl .) at /usr/bin/rancid line 49.
BEGIN failed--compilation aborted at /usr/bin/rancid line 49.
`
To fix that, you need to run inside a container following command:
`# apk add perl-socket6
`
After, all work perfect!

**Comment by biwhite** [comment]
Thanks, have added it into the Dockerfile.
